CSS-Three-Column-Layout challenge - Alvaro Diaz
alvarodiazjr/c0622-code-solutions pull request #18
Opened 2022-07-01 03:23 UTC by alvarodiazjr

<img width="1440" alt="Screen Shot 2022-06-30 at 8 18 02 PM" src="https://user-images.githubusercontent.com/103209321/176817220-56ae51b4-6ad8-423d-8ebd-962028fe82f5.png">

2022-07-01 17:40 UTC, codingcodymiller requested changes
Hey Alvaro! The text in each of your columns is too wide as compared to the example, please revise and submit a new screenshot with your revision

2022-07-01 20:28 UTC, alvarodiazjr commented
<img width="1440" alt="Screen Shot 2022-07-01 at 1 25 48 PM" src="https://user-images.githubusercontent.com/103209321/176964091-7f1563d9-98bb-44a8-a977-4ee54e64129a.png">

2022-07-01 22:01 UTC, codingcodymiller requested changes

2022-07-01 22:01 UTC, codingcodymiller commented on css-three-column-layout/styles.css
> +}
Why do you need a `column-one-third` and ` column-third` class? Also, the measurement for `column-two-thirds` is not accurate. These details **_really_** matter.

2022-07-01 22:01 UTC, codingcodymiller commented on css-three-column-layout/styles.css
> +}
You should check if the `justify-content` declaration here is necessary. If the property does nothing, it should be removed.

2022-07-01 23:39 UTC, codingcodymiller requested changes

2022-07-01 23:39 UTC, codingcodymiller commented on css-three-column-layout/styles.css
> +.column{
No, sorry, this is not what I intended. The name `column` give me no indication of its purpose. You need a column class for every size of `column` you use in your layout and a name that specifies its size. You should review the `css-layout-classes` exercise in depth to get a refresher on the concept.

2022-07-05 17:09 UTC, codingcodymiller approved these changes

2022-07-29 00:52 UTC, merged