CSS-Two-Column-Layout challenge - Alvaro Diaz
alvarodiazjr/c0622-code-solutions pull request #19
Opened 2022-07-01 05:39 UTC by alvarodiazjr

<img width="1440" alt="Screen Shot 2022-06-30 at 10 34 03 PM" src="https://user-images.githubusercontent.com/103209321/176830777-b71748d5-2fb7-4394-8b0b-fb4b42704543.png">

2022-07-01 17:50 UTC, codingcodymiller requested changes
Hey Alvaro, this output doesn't match the example in multiple ways, please revise this to match perfectly with the example.

2022-07-02 20:28 UTC, alvarodiazjr commented
<img width="1440" alt="Screen Shot 2022-07-02 at 1 26 07 PM" src="https://user-images.githubusercontent.com/103209321/177015314-9c948423-0c62-49a7-be1d-e811a7309f48.png">

2022-07-05 17:13 UTC, codingcodymiller requested changes

2022-07-05 17:13 UTC, codingcodymiller commented on css-two-column-layout/styles.css
> +  flex-basis: auto;
Shouldn't this be `66%` or `calc(200% / 3)`?

2022-07-06 16:25 UTC, codingcodymiller approved these changes

2022-07-29 00:52 UTC, merged