JavaScript-Light-Bulb - Alvaro Diaz
alvarodiazjr/c0622-code-solutions pull request #43
Opened 2022-07-12 22:40 UTC by alvarodiazjr

https://user-images.githubusercontent.com/103209321/178610373-a683cba6-96e9-4c3d-8392-eb04a1ef92cc.mov

2022-07-13 16:27 UTC, codingcodymiller requested changes

2022-07-13 16:27 UTC, codingcodymiller commented on javascript-light-bulb/main.js
> +  if($button.className === 'button-color light' && $pageColor.className === 'html light'){
By doing it this way, the action you take in your JavaScript is dependent on checking the current state of the element, which means your JavaScript is reliant on information from another language to know what to do. Instead, you should make a variable to keep track of if the light is currently on or off, and use that variable's value to determine what action to take on the DOM

2022-07-18 16:13 UTC, codingcodymiller requested changes

2022-07-18 16:13 UTC, codingcodymiller commented on javascript-light-bulb/main.js
> +  if(clicks % 2 !== 0){
A count of the clicks will work here, but you are keeping track of a count and just determining if that count is even or odd, one of two states. A boolean would be a better way to keep track of whether something is one of two different states. You should make a variable to keep track of if the light is currently on, with a boolean value.

2022-08-18 13:47 UTC, thebearingedge approved these changes

2022-08-18 16:56 UTC, merged