JavaScript-Timers - Alvaro Diaz
alvarodiazjr/c0622-code-solutions pull request #61
Opened 2022-07-27 18:06 UTC by alvarodiazjr

https://user-images.githubusercontent.com/103209321/181341850-a2c39145-5747-4a9a-abbc-91cb57a632bf.mov

https://user-images.githubusercontent.com/103209321/181341869-9af2a347-5e6e-4022-a3a0-517cde18d98d.mov

2022-07-27 18:38 UTC, codingcodymiller requested changes

2022-07-27 18:38 UTC, codingcodymiller commented on javascript-timers/interval.js
> +  } else if ($countdown.textContent === '1'){
What if the timer started from 1000? You should try to find a way to do this that doesn't require a conditional for each number.

2022-07-27 18:38 UTC, codingcodymiller commented on javascript-timers/interval.js
> +    $countdown.textContent = '~Earth Beeeelooowww Us~';
Don't forget to clear your interval

2022-08-19 14:20 UTC, thebearingedge approved these changes

2022-08-19 16:57 UTC, merged