Express-Notes-API Exercise - Alvaro Diaz
alvarodiazjr/c0622-code-solutions pull request #92
Opened 2022-08-23 00:51 UTC by alvarodiazjr

<img width="1233" alt="Screen Shot 2022-08-22 at 5 33 29 PM" src="https://user-images.githubusercontent.com/103209321/186044185-2ce82272-5657-4be5-b3a8-455d3119aea0.png">
<img width="954" alt="Screen Shot 2022-08-22 at 5 34 50 PM" src="https://user-images.githubusercontent.com/103209321/186044433-81e9c0db-784a-4744-8308-67c84bc667a8.png">
<img width="1001" alt="Screen Shot 2022-08-22 at 5 37 52 PM" src="https://user-images.githubusercontent.com/103209321/186044474-331ef05d-8d34-4b64-8235-07d01e9d3e5c.png">
<img width="994" alt="Screen Shot 2022-08-22 at 5 39 57 PM" src="https://user-images.githubusercontent.com/103209321/186044553-f2e9b784-c17d-4b73-80d0-ccd4c2760815.png">
<img width="1027" alt="Screen Shot 2022-08-22 at 5 43 01 PM" src="https://user-images.githubusercontent.com/103209321/186044607-e498bf01-b3ec-4b76-bda5-3c9a66ec1eb6.png">

2022-08-23 17:37 UTC, TimelikeClosure requested changes

2022-08-23 17:37 UTC, TimelikeClosure commented on express-notes-api/index.js
> +    res.status(400).json({ error: 'id must be a positive integer' });
Any non-positive-integer id should result in a `400 Bad Request` (for example, `GET /api/notes/-4353.354ugfdgjk`).

2022-08-23 17:37 UTC, TimelikeClosure commented on express-notes-api/index.js
> +  });
Don't send a successful response until after the write is successfully recorded.

2022-08-23 18:10 UTC, alvarodiazjr commented
<img width="956" alt="Screen Shot 2022-08-23 at 10 47 13 AM" src="https://user-images.githubusercontent.com/103209321/186232837-4ec3c34c-5ea2-49a3-a767-e62689011997.png">
<img width="958" alt="Screen Shot 2022-08-23 at 10 51 54 AM" src="https://user-images.githubusercontent.com/103209321/186232853-6e675340-cb1d-47c3-99f4-de1ae91ba4aa.png">

2022-08-23 20:09 UTC, TimelikeClosure requested changes

2022-08-23 20:09 UTC, TimelikeClosure commented on express-notes-api/index.js
> +    res.status(400).json({ error: 'id must be a positive integer' });
Don't forget to verify the id is positive. Also, non-integer numbers should result in a `400 Bad Request` (for example: `PUT /api/notes/354.646hfhf`), so try not to coerce values into integers.

2022-08-23 23:01 UTC, TimelikeClosure requested changes

2022-08-23 23:01 UTC, TimelikeClosure commented on express-notes-api/index.js
> +  next();
Please don't call `next()` in middleware unless you need additional middleware to run on the same request.

2022-08-23 23:01 UTC, TimelikeClosure commented on express-notes-api/index.js
> +    res.status(400).json({ error: 'id must be a positive integer' });
Please make sure you respond with a `400 Bad Request` when the id isn't an integer, rather than trying to correct it (example: `GET /api/notes/234.62346kgafd` should result in a `400 Bad Request`, not a `200 OK` or a `404 Not Found`).

---

![image](https://user-images.githubusercontent.com/16143771/186280728-6b1fc81c-a37e-4cc6-8656-f95dd16effa7.png)

2022-08-24 00:37 UTC, TimelikeClosure approved these changes

2022-08-24 03:56 UTC, merged